---

- name: Install prerequisites
  ansible.builtin.dnf:
    name:
      - python3-dnf
    state: present
  become: true

- name: Update all packages
  ansible.builtin.dnf:
    name: '*'
    state: latest
  become: true

- name: Check if reboot is required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_file

- name: Reboot the system if required
  ansible.builtin.reboot:
    msg: "Rebooting to apply package updates"
    reboot_timeout: 300
  become: true
  when: reboot_file.stat.exists
